apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: elastic-local-driver
  namespace: elastic-local
spec:
  template:
    metadata:
      name: elastic-local-driver
      labels:
        app: elastic-local-driver
    spec:
      serviceAccountName: elastic-local
      containers:
      - image: localhost:5000/elastic-cloud-dev/elastic-local:latest
        imagePullPolicy: Always
        name: elastic-local-driver
        args: ["driver"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /flexbin
          name: flexbin
        - mountPath: /var/run/elastic-local
          name: socket
        - name: dev
          mountPath: /dev
        - name: run
          mountPath: /run
        - mountPath: /mnt/elastic-local-volumes
          name: volumes
          mountPropagation: Bidirectional
        - mountPath: /var/lib/kubelet/pods
          name: kubelet-pods
          mountPropagation: Bidirectional
      volumes:
      - name: flexbin
        # directory where to copy the driver client binary, to be called by kubelet
        hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      - name: socket
        # directory where a socket will be created, to handle client-daemon communication
        hostPath:
          path: /var/run/elastic-local
      - name: dev
        # used to manage lvm devices
        hostPath:
          path: /dev
      - name: run
        # lock files for LVM
        hostPath:
          path: /run
      - name: volumes
        # one directory per persistent volume will be created there
        hostPath:
          path: /mnt/elastic-local-volumes
      - name: kubelet-pods
        # persistent volumes will be bind-mounted into the pod FS
        hostPath:
          path: /var/lib/kubelet/pods
