kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pvc-sample
  containers:
  - name: pv-container
    volumeMounts:
    - mountPath: "/data"
      name: pv-storage
    image: busybox
    command: ["sh"]
    args: ["-c", "while true; do echo $(date +%s) >> /data/containerfile; sleep 2; done"]