apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-local-provisioner
  namespace: elastic-local
  labels:
    app: elastic-local-provisioner
spec:
  selector:
    matchLabels:
      app: elastic-local-provisioner
  template:
    metadata:
      name: elastic-local-provisioner
      labels:
        app: elastic-local-provisioner
    spec:
      serviceAccountName: elastic-local
      containers:
      - name: elastic-local-provisioner
        image: $IMG
        imagePullPolicy: Always
        args: ["provisioner"]
